//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fluent.Xml.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Xmls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Xmls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fluent.Xml.Tests.Resources.Xmls", typeof(Xmls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;FluentXml&gt;
        ///  &lt;Author Id=&quot;10&quot;&gt;Ricardo Alves&lt;/Author&gt;
        ///  &lt;PackageName&gt;FluentXml&lt;/PackageName&gt;
        ///  &lt;Description&gt;This library is awesome =D&lt;/Description&gt;
        ///&lt;/FluentXml&gt;.
        /// </summary>
        internal static string fluentxml_xml {
            get {
                return ResourceManager.GetString("fluentxml_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Movies&gt;
        ///  &lt;Total&gt;3&lt;/Total&gt;
        ///  &lt;Year&gt;2016&lt;/Year&gt;
        ///  &lt;MoviesList&gt;
        ///    &lt;Movie&gt;
        ///      &lt;Name&gt;Justin Timberlake + The Tennessee Kids&lt;/Name&gt;
        ///      &lt;Description&gt;Jonathan Demme&apos;s acclaimed career may include numerous beloved dramas and comedies—from Something Wild and Married to the Mob to The Silence of the Lambs, Philadelphia, and Rachel Getting Married—but he&apos;s also the world&apos;s foremost music-concert documentarian. In the grand tradition of Stop Making Sense and Neil Y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string movies_2016_xml {
            get {
                return ResourceManager.GetString("movies_2016_xml", resourceCulture);
            }
        }
    }
}
